quote_list = [
    "I'm a reasonable guy. But, I've just experienced some very unreasonable things.",
    "May the wings of liberty never lose a feather.",
    "Everybody relax, I'm here.",
    "You go off to rule the universe from beyond the grave or check into a psycho ward, whichever comes first, huh?",
    "Sooner or later, I rub everybody the wrong way.",
    "Are you crazy? Is that your problem?",
    "Okay. You people sit tight, hold the fort, and keep the home fires burning. And if we're not back by dawn, call the president.",
    "I was born ready!",
    "Henry Swanson's my name, and excitement's my game.",
    "This is Jack Burton in the Pork Chop Express, and I'm talking to whoever's listening out there.",
    "Just remember what ol' Jack Burton does when the earth quakes, and the poison arrows fall from the sky, and the pillars of Heaven shake. Yeah, Jack Burton just looks that big ol' storm right square in the eye, and he says, 'Give me your best shot, pal. I can take it.'",
    "We really shook the pillars of heaven, didn't we, Wang?",
    "Like I told my last wife, I say, 'Honey, I never drive faster than I can see. Besides that, it's all in the reflexes.'",
    "Terrific, a six-demon bag. Sensational. What's in it, Egg?",
    "When some wild-eyed, eight-foot-tall maniac grabs your neck, taps the back of your favorite head up against the bathroom wall, looks you crooked in the eye, and asks you if you paid your dues. You just stare that big sucker right back in the eye, and you remember what ol' Jack Burton always says at a time like that, 'Have you paid your dues, Jack?' 'Yes, sir, the check is in the mail.'",
    "What's in the flask, Egg? Magic potion? Thought so, good, what do we do? Drink it?",
    "Which Lo Pan? Little old basket case on wheels or the 10-foot-tall roadblock?",
    "Oh, okay. I won't, Wang! Let's just chew our way out of here.",
    "Jack Burton, me! Ol' Jack always says, 'What the hell.'",
    "Gracie Law: I'd go with you, but—. Jack Burton: I know, there's a problem with your face.",
    "You got a tongue, Dave. Ask her yourself.",
    "I took something. I can see things other men cannot see. Why are you dressed like that?",
    "Egg Shen: You will come out no more! Jack Burton: What? Huh? What'll come out no more?",
    "Tall guy, weird clothes. First, you see him. Then you don't.",
    "This is going to take crackerjack timing, Wang.",
    "If you have problem like that again, just reach for the sky!",
    "You just listen to the old Pork Chop Express here now and take his advice on a dark and stormy night when the lightning's crashing and the thunder's rolling and the rain's coming down in sheets thick as lead.",
    "Two, three feet thick, I'll bet. Probably welded shut from the outside and covered with brick by now!",
    "Not so fast, gentlemen! We got enough people dropping like flies around here, and where's that getting us, huh? Nowhere fast.",
    "Is this gonna get ugly, now? Huh? I hope not. Because I thought what we were here, racial differences notwithstanding, was just a couple of old friends. You know, just both of us Californians.",
    "Damn right, you will. And my money and time is money to a guy like me, and your phone is dead, by the way.",
    "They got enemies?",
    "Feel pretty good. I'm not, uh, I'm not scared at all. I just feel kind of, feel kind of invincible.",
    "One, two, three, we may be trapped.",
    "Hey, don't worry, I can handle him.",
    "Abandoned like hell!",
    "Oh gosh, cash, I guess. I mean, it's not deductible, is it.",
    "Wang, these guys, these Sing Dings.",
    "What does that say? You're kidding.",
    "Is it getting hot in here, or is it just me?",
    "Yeah, right. Over my dead body.",
    "Margo Litzenberger: God, aren't you even gonna kiss her goodbye? Jack Burton: Nope.",
]
